### ISSUE TITLE
Migrate / transition to a Greenwood Theme Pack

### ISSUE THREAD

**Issue by thescientist13** [thescientist13/greenwood-starter-presentation#13]
## Type of Change
- [x] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
This would effectively allow this repo to additionally be consumed as a package from npm in a Greenwood project using the ([soon to be released](https://github.com/ProjectEvergreen/greenwood/pull/669)) ["Theme Pack" capability](https://github.com/ProjectEvergreen/greenwood/issues/570).

## Details
This would require such tasks like
1. [x] Adopt Greenwood theme pack convention, figure out DX
    - Updating _package.json_ and creating a prerelease script to correct prepare templates and pages
1. [X] Validate in https://github.com/thescientist13/knowing-your-tco, push content to new repo
1. [x] Needs https://github.com/ProjectEvergreen/greenwood/pull/692
1. [x] _index.html_ override interim solution - https://github.com/ProjectEvergreen/greenwood/issues/681#issuecomment-896118727
1. [x] Updating _README.md_ to provide broad array of usage options
    - Installation
      -  "clone" and go with git
      - degit?
      - npm / Greenwood
      - copy / paste!
    - Usage (slides API)
    - comment on https://github.com/ProjectEvergreen/greenwood/discussions/610
1. [x] Contribute back to [Greenwood publishing discussion](https://github.com/ProjectEvergreen/greenwood/discussions/610)?
    - Further technical details about peer vs dev deps?
    - bundle dev dep plugins as part of the plugin itself!?  (reduce peers)
    - index / pages
1. [ ] Rename repo to theme?

## New Issues
1. [x] Add tests using [**gallinago**](https://github.com/thescientist13/gallinago) - https://github.com/thescientist13/greenwood-starter-presentation/issues/26
1. [x] Adopt truly encapsulated pages (MVP) - https://github.com/thescientist13/greenwood-starter-presentation/issues/24
1. [x] Figure out deps - https://github.com/thescientist13/greenwood-starter-presentation/issues/25
1. [x] Track supporting `yarn build` and `yarn serve` workflows (since our Netlify build is broken currently) - https://github.com/thescientist13/greenwood-starter-presentation/issues/27
